### ISSUE TITLE
Connection error when the computer is setup to use a comma (,) as decimal separator

### ISSUE THREAD

**Issue by HuubBuis** [MetalWorkerTools/CNCR#2]
Currently the gcodes sent to the controller use the Windows decimal separator. This will lead to problems (can't connect) if you computer is setup to use a comma (,) as decimal separator. 

This will be fixed today but it probably will take a few days (holiday time) for Microsoft to approve a new release.

As a workaround, you can setup your computer to use a dot (.) as decimal separator. Beware, this could lead to problems when using other software.

**Comment by MetalWorkerTools** [comment]
I have release an update that should fix this issue. I can't however reproduce this problem on my PC's.

**Comment by HuubBuis** [comment]
After January 2022 update, no more reports of this problem, closing issue.
